sudo: required
language: node_js
cache: yarn
node_js:
- '5'
before_install:
- gem install sass
- gem install ruby
- gem install scss_lint
- npm install -g yarn
- npm install promise
before_script:
- yarn install
script:
- yarn test
